// src/utils/iconUtils.tsx
import {
  Award,
  Baby,
  Bike,
  Book,
  Briefcase,
  Building,
  Bus,
  Calculator,
  Calendar,
  Camera,
  Car,
  Clock,
  Cloud,
  Coffee,
  CreditCard,
  Crown,
  DollarSign,
  Dumbbell,
  FileText,
  Film,
  Fuel,
  Gamepad2,
  Gem,
  Gift,
  GraduationCap,
  HardHat,
  Headphones,
  Heart,
  Home,
  IceCream,
  Laptop,
  MapPin,
  Monitor,
  Moon,
  MoreHorizontal,
  Music,
  Package,
  Palette,
  PawPrint,
  Phone,
  PiggyBank,
  Pill,
  Pizza,
  Plane,
  Receipt,
  Scissors,
  ShieldCheck,
  Shirt,
  ShoppingCart,
  Smartphone,
  Star,
  Stethoscope,
  Sun,
  Target,
  Train,
  TreePine,
  TrendingUp,
  Umbrella,
  Utensils,
  Wallet,
  Wine,
  Wrench,
  Zap,
} from 'lucide-react';

// Icon mapping object
const iconMap = {
  home: Home,
  wallet: Wallet,
  'dollar-sign': DollarSign,
  'credit-card': CreditCard,
  'piggy-bank': PiggyBank,
  'trending-up': TrendingUp,
  calculator: Calculator,
  receipt: Receipt,
  utensils: Utensils,
  coffee: Coffee,
  pizza: Pizza,
  'ice-cream': IceCream,
  wine: Wine,
  car: Car,
  fuel: Fuel,
  bus: Bus,
  bike: Bike,
  train: Train,
  plane: Plane,
  'shopping-cart': ShoppingCart,
  shirt: Shirt,
  gift: Gift,
  package: Package,
  film: Film,
  music: Music,
  gamepad2: Gamepad2,
  camera: Camera,
  palette: Palette,
  heart: Heart,
  dumbbell: Dumbbell,
  stethoscope: Stethoscope,
  pill: Pill,
  baby: Baby,
  'paw-print': PawPrint,
  scissors: Scissors,
  briefcase: Briefcase,
  book: Book,
  'graduation-cap': GraduationCap,
  laptop: Laptop,
  smartphone: Smartphone,
  monitor: Monitor,
  headphones: Headphones,
  zap: Zap,
  phone: Phone,
  wrench: Wrench,
  'hard-hat': HardHat,
  'shield-check': ShieldCheck,
  'map-pin': MapPin,
  building: Building,
  'tree-pine': TreePine,
  umbrella: Umbrella,
  calendar: Calendar,
  clock: Clock,
  target: Target,
  award: Award,
  star: Star,
  crown: Crown,
  gem: Gem,
  'file-text': FileText,
  sun: Sun,
  moon: Moon,
  cloud: Cloud,
  'more-horizontal': MoreHorizontal,
};

// Function to get icon component by name
export const getIconComponent = (iconName: string) => {
  return iconMap[iconName as keyof typeof iconMap] || MoreHorizontal;
};
